import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'Tutorial' }],
  dockerSidebar: [{ type: 'autogenerated', dirName: 'Docker' }],
  tsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'TypeScript'
    }
  ],
  reactSidebar: [
    'react',
    {
      type: 'autogenerated',
      dirName: 'React'
    }
  ],
  jsSidebar: [
    'javascript',
    {
      type: 'autogenerated',
      dirName: 'JavaScript'
    }
  ],
  vueSidebar: [
    'vue',
    {
      type: 'autogenerated',
      dirName: 'Vue'
    }
  ],
  liunxSidebar: [
    'liunx',
    {
      type: 'autogenerated',
      dirName: 'Liunx'
    }
  ],
  pySidebar: [
    {
      type: 'autogenerated',
      dirName: 'Python'
    }
  ],
  hcSidebar: [
    'html-and-css',
    {
      type: 'autogenerated',
      dirName: 'HTML-and-CSS'
    }
  ],
  otherSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Other'
    }
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro', // 指向项目 docs/ 目录下的 intro.md 文件
    'hello', // 指向 docs/hello.md 文件
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
